package com.example.simcard.db;

import android.annotation.SuppressLint;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

@SuppressLint("SimpleDateFormat")
public class SaleOrder {

	// <SaleOrder>

	// <dt>29/09/2014</dt>

	// <AgentId>6047</AgentId>
	// <BuyerId>37539</BuyerId>
	// <LocationId>32732</LocationId>
	// <Description></Description>
	// <OrderType>2</OrderType>
	// <OrderStatus>1</OrderStatus>
	// <UId>fbf17b64-6d29-4397-8299-5fd966fffac9</UId>
	// <Id></Id>
	// <Cards>
	// <Card>
	// <Sn>1</Sn>
	// <NominalId>156</NominalId>
	// </Card>
	// <Card>
	// <Sn>2</Sn>
	// <NominalId>156</NominalId>
	// </Card>
	// </Cards>
	// </SaleOrder>

	public Date dt; 
	public Agent agent;
	public Buyer buyer;
	public Location location;
	public String Description;
	public int OrderType; // 1 is sim card order, 2 - is scratch card order
							// (vaucher)
	public int OrderStatus = 1;
	private String UId; // autogenerated guid
	public String errorMessage = "";

	public int id = -1;

	public List<Card> listOfCards;
	public int cards = 0;

	public int getCards() {
		if (listOfCards != null) {
			return listOfCards.size();
		} else {
			return cards;
		}
	}

	public void setCards(int cards) {
		this.cards = cards;
	}

	// a temporary variable for listView
	public boolean isSelected = false;


	public SaleOrder(int id, Date dt, Agent agent, Buyer buyer,
			Location location, String description, int orderType,
			int orderStatus, String errorMessage, String uId,
			List<Card> listOfCards, int cards) {
		super();
		this.id = id;
		this.dt = dt;
		this.agent = agent;
		this.buyer = buyer;
		this.location = location;
		Description = description;
		OrderType = orderType;
		OrderStatus = orderStatus;
		this.UId = uId;
		this.listOfCards = listOfCards;
		this.cards = cards;
		this.errorMessage = errorMessage;
	}

	public SaleOrder() {
		super();
		this.UId = java.util.UUID.randomUUID().toString();
	}

	public SaleOrder(String UId) {
		super();
		this.UId = UId;
	}

	public String getUId() {
		return UId;
	}

	@Override
	public String toString() {
		return "SaleOrder [id=" + id + ", dt=" + dt + ", agent=" + agent
				+ ", buyer=" + buyer + ", location=" + location
				+ ", Description=" + Description + ", OrderType=" + OrderType
				+ ", OrderStatus=" + OrderStatus + ", UId=" + UId
				+ ", errorMessage=" + errorMessage + ", listOfCards="
				+ listOfCards + ", cards=" + cards + ", isSelected="
				+ isSelected + "]";
	}

	public String getDtString() {
		final SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
		return df.format(dt);
	}

	public int getAgentId() {
		return agent.value;
	}

	public int getBuyerId() {
		return buyer.id;
	}

	public int getLocationId() {
		return location.id;
	}

}
